controlWork_9/Controllers/ProfilesController.cs
using controlWork_9.Extensions;
using controlWork_9.Models;
using controlWork_9.Services.UsersServices.Abstracts;
using controlWork_9.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace controlWork_9.Controllers;

[Authorize]
public class ProfilesController : Controller
{
    private readonly IUserService _userService;

    public ProfilesController(IUserService userService)
    {
        _userService = userService;
    }

    [HttpGet]
    public async Task<IActionResult> Profile(string? userName)
    {
        if (userName is null || User.Identity.Name != userName) 
            return NotFound();

        User? totalUser = await _userService.FindByEmailOrLoginAsync(userName);
        ProfileViewModel model = totalUser.MapToProfileViewModel();
        
        return View(model);
    }

}

controlWork_9/Controllers/TransactionsController.cs
using controlWork_9.Services.TransactionsService.Abstract;
using controlWork_9.ViewModels.Accounts;
using controlWork_9.ViewModels.Providers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace controlWork_9.Controllers;

public class TransactionsController : Controller
{
    private readonly ITransactionService _transactionService;

    public TransactionsController(ITransactionService transactionService)
    {
        _transactionService = transactionService;
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [AllowAnonymous]
    public async Task<IActionResult> TopUpAccount(TopUpAccountViewModel model)
    {
        if (ModelState.IsValid)
        {
            if (User.Identity.IsAuthenticated)
            {
                model.AccountNumber = User.Identity.Name;
            }
            bool result = await _transactionService.TopUpAccount(model);
            if (result)
            {
                return Ok("Счет пополнен");
            }
        }

        return BadRequest("Произошла ошибка при пополнеии счета");
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SendMoney(SendMoneyViewModel model)
    {
        if (ModelState.IsValid)
        {
            if (User.Identity.Name.Equals(model.AccountNumber))
            {
                return BadRequest("Нельзя перевести на свой же текущий счет");
            }
            bool result = await _transactionService.SendMoney(model);
            if (result)
            {
                return Ok("Операция успешно проведена");
            }
        }

        return BadRequest("Произошла ошибка при переводе");
    }
    
    [HttpGet]
    [Authorize]
    public IActionResult PayProviders()
    {
        PayProviderViewModel model = _transactionService.GetAllProviders();

        return View(model);
    }
    
    [HttpPost]
    [Authorize]
    public async Task<IActionResult> PayProviders(PayProviderViewModel model)
    {
        if (ModelState.IsValid)
        {
            bool result = await _transactionService.PayProvider(model, User.Identity.Name);
            if (result)
            {
                return Ok();
            }
        }

        return BadRequest("Ошибка при оплате проверьте правильность введеного лицевого счета");
    }
}

controlWork_9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - controlWork_9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/controlWork_9.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">Главная</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-route-userName="@User.Identity.Name" asp-controller="Profiles" asp-action="Profile">Профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="PayProviders">Опалата услуг</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @Html.AntiForgeryToken()
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - controlWork_9 - <a asp-area="" asp-controller="" asp-action="">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/topUpAccount.js" asp-append-version="true"></script>
<script src="~/js/sendMoney.js" asp-append-version="true"></script>
<script src="~/js/payProvider.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>